# Trust-policy snapshot test for OIDC federation roles.
#
# Asserts that aws_iam_role.federation produces a trust policy that:
#   - Uses StringEquals only (never StringLike)
#   - Contains exactly one :aud and one :sub condition key per role
#   - References the OIDC provider by ARN (oidc-provider/<issuer-host>)
#   - Has Action = sts:AssumeRoleWithWebIdentity
#   - Has the correct sub value for the crossplane-provider-aws ServiceAccount
#
# Design Decision #7 in docs/ARCHITECTURE_AND_DESIGN-OIDC.md:
#   The StringLike prohibition is the highest-impact security control. This test
#   is the automated enforcement layer; PR review is defense-in-depth only.
#
# Prerequisites for running locally or in CI:
#   1. Terraform >= 1.7.0 (mock_provider support)
#   2. Terraform >= 1.8.0 (templatestring function used in the module)
#   3. A stub locals-aft.tf defining local.aft_management_account_id must exist
#      in baseline/terraform/. In CI this is generated by oidc-validate.yml.
#      Locally: echo 'locals { aft_management_account_id = "000000000000" }' \
#                 > baseline/terraform/locals-aft.tf
#   4. Run: terraform -chdir=baseline/terraform test

# ---------------------------------------------------------------------------
# Mock provider
# Replaces the AWS provider with a built-in mock. No real AWS credentials or
# API calls are needed. Explicit mock_resource and mock_data blocks supply
# deterministic values so assertions can reference them by content.
# ---------------------------------------------------------------------------

mock_provider "aws" {
  mock_resource "aws_iam_openid_connect_provider" {
    defaults = {
      arn = "arn:aws:iam::123456789012:oidc-provider/oidc.k8s.occ.ottawacloudconsulting.com"
      url = "oidc.k8s.occ.ottawacloudconsulting.com"
    }
  }

  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "123456789012"
    }
  }

  mock_data "aws_region" {
    defaults = {
      name        = "ca-central-1"
      description = "Canada (Central)"
    }
  }
}

# ---------------------------------------------------------------------------
# Default variables — applied to all run blocks unless overridden.
# ---------------------------------------------------------------------------

variables {
  oidc_federation_enabled = true
  # Minimal valid 40-char hex SHA-1 thumbprint (satisfies the validation block).
  oidc_thumbprints = ["a94a8fe5ccb19ba61c4c0873d391e987982fbbd3"]
}

# ---------------------------------------------------------------------------
# Run 1: Trust-policy structure assertions
# ---------------------------------------------------------------------------

run "trust_policy_uses_stringequals_only" {
  command = plan

  # No StringLike anywhere in the trust policy JSON.
  assert {
    condition     = !can(regex("StringLike", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy))
    error_message = "Trust policy must not use StringLike. Only StringEquals is permitted for OIDC trust conditions. StringLike enables wildcard matching on sub or aud claims and can allow cross-tenant token acceptance. See Design Decision #7."
  }

  # StringEquals is the sole condition operator.
  assert {
    condition     = can(regex("StringEquals", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy))
    error_message = "Trust policy must use StringEquals for both :aud and :sub condition keys."
  }

  # Exactly one :aud condition key.
  assert {
    condition     = length(regexall(":aud\"", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy)) == 1
    error_message = "Trust policy must have exactly one :aud condition key."
  }

  # Exactly one :sub condition key.
  assert {
    condition     = length(regexall(":sub\"", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy)) == 1
    error_message = "Trust policy must have exactly one :sub condition key."
  }

  # Condition keys are prefixed with the OIDC issuer hostname (from resource attribute, not var).
  assert {
    condition     = can(regex("oidc\\.k8s\\.occ\\.ottawacloudconsulting\\.com:aud", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy))
    error_message = "The :aud condition key must be prefixed with the OIDC issuer hostname from the provider resource attribute (aws_iam_openid_connect_provider.this[0].url)."
  }

  assert {
    condition     = can(regex("oidc\\.k8s\\.occ\\.ottawacloudconsulting\\.com:sub", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy))
    error_message = "The :sub condition key must be prefixed with the OIDC issuer hostname from the provider resource attribute (aws_iam_openid_connect_provider.this[0].url)."
  }

  # Action is sts:AssumeRoleWithWebIdentity.
  assert {
    condition     = can(regex("AssumeRoleWithWebIdentity", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy))
    error_message = "Trust policy Action must be sts:AssumeRoleWithWebIdentity."
  }

  # Federated principal references the OIDC provider ARN (not a string-interpolated ARN).
  assert {
    condition     = can(regex("oidc-provider/oidc\\.k8s\\.occ\\.ottawacloudconsulting\\.com", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy))
    error_message = "Trust policy Federated principal must reference the OIDC provider ARN (aws_iam_openid_connect_provider.this[0].arn). Do not construct the ARN via string interpolation of var.oidc_issuer_url. See Design Decision #8."
  }

  # sub value matches the crossplane-provider-aws ServiceAccount.
  assert {
    condition     = can(regex("system:serviceaccount:crossplane-provider-aws:provider-aws-iam", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy))
    error_message = "Trust policy sub condition must equal 'system:serviceaccount:crossplane-provider-aws:provider-aws-iam' (from crossplane-aws-iam.json wrapper). See REQUIREMENTS-OIDC.md §R2.1."
  }
}

# ---------------------------------------------------------------------------
# Run 2: Feature flag off produces no resources
# ---------------------------------------------------------------------------

run "feature_flag_off_produces_no_resources" {
  command = plan

  variables {
    oidc_federation_enabled = false
    oidc_thumbprints        = []
  }

  assert {
    condition     = length(aws_iam_openid_connect_provider.this) == 0
    error_message = "No OIDC provider should be created when oidc_federation_enabled is false. Zero state churn is the default behavior."
  }

  assert {
    condition     = length(aws_iam_role.federation) == 0
    error_message = "No federation roles should be created when oidc_federation_enabled is false."
  }
}
