# Trust-policy snapshot test for OIDC federation roles.
#
# Asserts that aws_iam_role.federation produces a trust policy that:
#   - Uses StringEquals only (never StringLike)
#   - Contains exactly one :aud and one :sub condition key per role
#   - References the OIDC provider by ARN (oidc-provider/<issuer-host>)
#   - Has Action = sts:AssumeRoleWithWebIdentity
#   - Has the correct sub value for the crossplane-provider-aws ServiceAccount
#
# Design Decision #7 in docs/oidc/ARCHITECTURE_AND_DESIGN.md:
#   The StringLike prohibition is the highest-impact security control. This test
#   is the automated enforcement layer; PR review is defense-in-depth only.
#
# Prerequisites for running locally or in CI:
#   1. Terraform >= 1.7.0 (mock_provider support)
#   2. Terraform >= 1.8.0 (templatestring function used in the module)
#   3. A stub locals-aft.tf defining local.aft_management_account_id must exist
#      in baseline/terraform/. In CI this is generated by oidc-validate.yml.
#      Locally: echo 'locals { aft_management_account_id = "000000000000" }' \
#                 > baseline/terraform/locals-aft.tf
#   4. Run: terraform -chdir=baseline/terraform test

# ---------------------------------------------------------------------------
# Mock provider
# Replaces the AWS provider with a built-in mock. No real AWS credentials or
# API calls are needed. Explicit mock_resource and mock_data blocks supply
# deterministic values so assertions can reference them by content.
# ---------------------------------------------------------------------------

mock_provider "aws" {
  mock_resource "aws_iam_openid_connect_provider" {
    defaults = {
      arn = "arn:aws:iam::123456789012:oidc-provider/oidc.k8s.occ.ottawacloudconsulting.com"
      url = "oidc.k8s.occ.ottawacloudconsulting.com"
    }
  }

  # AWS IAM validates permissions_boundary as an ARN at apply time; the default
  # mock_resource arn placeholder ("j738tl5q") fails that validation. Supply a
  # well-formed ARN so apply succeeds for both the federation roles and the
  # baseline deployment roles that reference the same boundary.
  mock_resource "aws_iam_policy" {
    defaults = {
      arn = "arn:aws:iam::123456789012:policy/Boundary-Default"
    }
  }

  # Federation roles attach an inline aws_iam_role_policy with policy rendered
  # via templatestring(); mock the resource so apply does not require a real
  # API call to materialize the policy attribute.
  mock_resource "aws_iam_role" {
    defaults = {
      arn = "arn:aws:iam::123456789012:role/mock-role"
    }
  }

  mock_data "aws_caller_identity" {
    defaults = {
      account_id = "123456789012"
      arn        = "arn:aws:iam::123456789012:root"
      user_id    = "123456789012"
    }
  }

  mock_data "aws_region" {
    defaults = {
      region      = "ca-central-1"
      description = "Canada (Central)"
    }
  }
}

# ---------------------------------------------------------------------------
# Default variables — applied to all run blocks unless overridden.
# ---------------------------------------------------------------------------

variables {
  oidc_federation_enabled = true
  # Minimal valid 40-char hex SHA-1 thumbprint (satisfies the validation block).
  oidc_thumbprints = ["a94a8fe5ccb19ba61c4c0873d391e987982fbbd3"]
  # Security-tier account IDs — mock values distinct from the caller_identity
  # mock (123456789012), so the current account is NOT treated as a security-
  # tier account and the OIDC provider is created. Cross-variable validation
  # on these variables requires non-empty 12-digit IDs whenever
  # oidc_federation_enabled = true.
  audit_account_id       = "210987654321"
  log_archive_account_id = "098765432109"
}

# ---------------------------------------------------------------------------
# Run 1: Trust-policy structure assertions
# ---------------------------------------------------------------------------

run "trust_policy_uses_stringequals_only" {
  # apply (not plan) is required because the trust-policy assertions reference
  # aws_iam_role.federation[...].assume_role_policy, which is the result of
  # jsonencode() over the OIDC provider's arn and url attributes. Those
  # attributes are unknown at plan time even with mock_provider defaults; the
  # mock values are materialized during apply.
  command = apply

  # No StringLike anywhere in the trust policy JSON.
  assert {
    condition     = !can(regex("StringLike", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy))
    error_message = "Trust policy must not use StringLike. Only StringEquals is permitted for OIDC trust conditions. StringLike enables wildcard matching on sub or aud claims and can allow cross-tenant token acceptance. See Design Decision #7."
  }

  # StringEquals is the sole condition operator.
  assert {
    condition     = can(regex("StringEquals", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy))
    error_message = "Trust policy must use StringEquals for both :aud and :sub condition keys."
  }

  # Exactly one :aud condition key.
  assert {
    condition     = length(regexall(":aud\"", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy)) == 1
    error_message = "Trust policy must have exactly one :aud condition key."
  }

  # Exactly one :sub condition key.
  assert {
    condition     = length(regexall(":sub\"", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy)) == 1
    error_message = "Trust policy must have exactly one :sub condition key."
  }

  # Condition keys are prefixed with the OIDC issuer hostname (from resource attribute, not var).
  assert {
    condition     = can(regex("oidc\\.k8s\\.occ\\.ottawacloudconsulting\\.com:aud", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy))
    error_message = "The :aud condition key must be prefixed with the OIDC issuer hostname from the provider resource attribute (aws_iam_openid_connect_provider.this[0].url)."
  }

  assert {
    condition     = can(regex("oidc\\.k8s\\.occ\\.ottawacloudconsulting\\.com:sub", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy))
    error_message = "The :sub condition key must be prefixed with the OIDC issuer hostname from the provider resource attribute (aws_iam_openid_connect_provider.this[0].url)."
  }

  # Action is sts:AssumeRoleWithWebIdentity.
  assert {
    condition     = can(regex("AssumeRoleWithWebIdentity", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy))
    error_message = "Trust policy Action must be sts:AssumeRoleWithWebIdentity."
  }

  # Federated principal references the OIDC provider ARN (not a string-interpolated ARN).
  assert {
    condition     = can(regex("oidc-provider/oidc\\.k8s\\.occ\\.ottawacloudconsulting\\.com", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy))
    error_message = "Trust policy Federated principal must reference the OIDC provider ARN (aws_iam_openid_connect_provider.this[0].arn). Do not construct the ARN via string interpolation of var.oidc_issuer_url. See Design Decision #8."
  }

  # sub value matches the crossplane-provider-aws ServiceAccount.
  assert {
    condition     = can(regex("system:serviceaccount:crossplane-provider-aws:provider-aws-iam", aws_iam_role.federation["crossplane-aws-iam"].assume_role_policy))
    error_message = "Trust policy sub condition must equal 'system:serviceaccount:crossplane-provider-aws:provider-aws-iam' (from crossplane-aws-iam.json wrapper). See REQUIREMENTS-OIDC.md §R2.1."
  }
}

# NOTE: A second run block for the feature-flag-off case (asserting that
# count = 0 produces zero OIDC resources) was removed from this file.
# Reason: the OIDC provider and federation roles carry
# `lifecycle { prevent_destroy = true }` (intentional production behavior).
# In a single test file, a later run with flag=false produces a destroy plan
# for the resources created by the earlier flag=true apply, which Terraform
# rejects at plan time with "Instance cannot be destroyed". The off-state
# behavior is also statically inspectable (count = local.oidc_provider_count
# and for_each = enabled ? roles : {}); it does not require dynamic test
# coverage. If a future maintainer wants apply-time coverage of the off path,
# move it into a separate test file so it gets its own state lifecycle.
